Repository trackhub/website, pull requests merged in 2019-08, with the labels that each got.

#81 way-point export
  src/Track/Exporter.php
Labels: enhancement

#84 0 point elevation fix
  script/migration/migrations/20190811183947_nullable_point_elev.php
  src/Entity/Track/PointTrait.php
  src/Track/Processor.php
  tests/phpunit/test/Track/ProcessorElevationTest.php
  tests/phpunit/test/Track/ProcessorTest.php
Labels: bug

#85 remove horizontal scroll
  templates/home/home.html.twig
Labels: bug

#87 Admins can't edit track details
  src/Controller/Track.php
Labels: bug

#88 allow users to edit own tracks
  script/migration/migrations/20190817161152_track_send_by.php
  src/Controller/Track.php
  src/Entity/Track.php
  src/Security/Authorization/Voter/TrackVoter.php
  tests/phpunit/test/Entity/TrackTest.php
Labels: enhancement

#89 Handle track edit errors
  src/Controller/Track.php
  src/Form/Type/Track.php
Labels: bug

#90 admin impr
  src/Admin/TrackAdmin.php
  src/Admin/UserAdmin.php
Labels: enhancement

#96 Track rating
  assets/css/global.scss
  assets/css/rating.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/debug.yaml
  config/routes.yaml
  package.json
  script/migration/migrations/20190818182608_user_rating.php
  src/Controller/Track.php
  src/Entity/Track/Version.php
  src/Entity/Track/VersionRating.php
  src/Entity/User/User.php
  symfony.lock
  templates/base.html.twig
  templates/gps/view.html.twig
  templates/include/foot.html.twig
  templates/include/head.html.twig
  webpack.config.js
  yarn.lock
Labels: enhancement

#99 temporary use dev-master in phinx
  script/migration/composer.json
Labels: bug

#102 Can't build production js
  package.json
  yarn.lock
Labels: bug

#107 Optimize js
  assets/js/app.js
  assets/js/components/appTrack.js
  assets/js/components/starRating.js
  assets/js/view.js
  templates/gps/view.html.twig
  templates/include/mapVersion.html.twig
  templates/include/ratingModal.html.twig
  webpack.config.js
Labels: optimization
