Repository trackhub/website, pull requests merged in 2019-09, with the labels that each got.

#117 JS error on track view page
  templates/gps/view.html.twig
Labels: bug

#118 JS lightbox is not working
  templates/gps/view.html.twig
Labels: bug

#119 Add track image send date
  script/migration/migrations/20190906152622_image_send_date.php
  src/Entity/Track/Image.php
Labels: enhancement

#121 export is broken
  src/Track/Exporter.php
Labels: bug

#122 Bugfixes
  README.md
  src/Admin/TrackAdmin.php
  src/Entity/Track.php
  tests/phpunit/test/Entity/TrackTest.php
Labels: bug

#120 Enable zoom with scrolling on full screen map
  assets/js/app.js
  assets/js/map/control/fullScreen.js
  templates/gps/view.html.twig
  templates/home/home.html.twig
Labels: enhancement

#125 seeders: Fix name fields
  script/migration/seeds/TrackSeeder.php
Labels: bug

#135 Youtube videos are lost after edit
  src/Controller/Track.php
  templates/gps/edit.html.twig
Labels: bug

#138 fix image orientation
  docker/web/Dockerfile
  src/Image/ImageEdit.php
Labels: bug

#139 Resizing all images
  .gitignore
  config/routes.yaml
  config/services.yaml
  src/Controller/Track/Image.php
  src/Image/ImageEdit.php
  src/Twig/TrackImageExtension.php
  templates/gps/view.html.twig
  templates/home/home.html.twig
  tests/phpunit/test/Twig/TrackImageExtensionTest.php
Labels: enhancement

#140 Add expire header for images
  docker/web/Dockerfile
  docker/web/virtualhost-ssl.conf
  docker/web/virtualhost.conf
Labels: optimization
